### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by arpit601** [timediv/speechT#11]
@timediv I am getting segmentation fault (core dumped) error while evaulating the model using language model (kenlm)

Starting input pipeline
Begin evaluation
Segmentation fault (core dumped)

**Comment by louiskirsch** [comment]
Please give information about

- version you are using
- system hardware
- kenlm tensorflow version
- files you are using for kenlm

I suspect you may have not enough RAM.

**Comment by arpit601** [comment]
@timediv version you are using -Ubuntu LTS 16.04
system hardware - 8 GPUs, 32vCPUs, 120GB ram
kenlm tensorflow version - used source code to install tensorflow with kenlm from github. 
files you are using for kenlm - binary , vocabulary and trie

**Comment by arpit601** [comment]
@timediv 
kenlm-english using bible that you have provided is running but it generates error when i try to use my kenlm folder that has binary, trie and vocabulary file .

**Comment by arpit601** [comment]
@timediv problem has been resolved. I think i was not using config= cuda while building the trie .

**Comment by louiskirsch** [comment]
Hum, I don't think that makes a difference. There must be something else going wrong. Can you inspect the core dump?

**Comment by arpit601** [comment]
How can i inspect the core dump ?

**Comment by louiskirsch** [comment]
Please reopen if you have more details about what is happening
