### ISSUE TITLE
tuneable parameters like word_count and valid_word_count_weight

### ISSUE THREAD

**Issue by arpit601** [timediv/speechT#13]
@timediv what could be the range of value for these parameters ? Is there any article where i can read more on it and can set them ?

**Comment by arpit601** [comment]
@timediv  any answer for the above query >???

**Comment by arpit601** [comment]
@timediv

**Comment by louiskirsch** [comment]
The KenLM language model results in longer sentences being less likely than shorter sentences.
To offset that, three parameters are introduced:
word_count_weight: additional score added for every new word in the beam
valid_word_count_weight: additional score for every new word in the beam that exists in the vocabulary
language_model_weight: the weight of the logprob the language model predicts within the beam scoring

**Comment by arpit601** [comment]
@timediv  In most of the papers, these all parameters are optimized using a validation set . How can I do that without choosing the values myself?

**Comment by louiskirsch** [comment]
I optimized those parameters on a validation set using `speecht-cli search` (local search).
The default parameters are therefore optimized already.
