### ISSUE TITLE
tensorflow version?

### ISSUE THREAD

**Issue by violeta7** [timediv/speechT#14]
Thank you for this great project.
Could you tell me which tensorflow version I have to install to run speechT?
1.0? 1.1? 0.9? older?

**Comment by arpit601** [comment]
You have to install tensorflow with kenlm from the git hub source code to run the  testing phase of the code.
https://github.com/timediv/tensorflow-with-kenlm

For training phase you can use 1.0 . So i would recommend you to use the above link to install the tensorflow.
