### ISSUE TITLE
Problem while testing the code

### ISSUE THREAD

**Issue by arpit601** [timediv/speechT#2]
File "/home/arpit_agrawal/test/speechT/speecht/evaluation.py", line 143, in run_epoch
decoded_ids = next(decoded_path)
StopIteration
I am getting this stopIteration error

**Comment by arpit601** [comment]
??? @timediv 
need your help urgently for this issue....

**Comment by louiskirsch** [comment]
Is this happening with your adapted code or the master version?

**Comment by arpit601** [comment]
master version

**Comment by arpit601** [comment]
I haven't changed anything in evaluation files. I changed only corpus.py and preprocessing.py and I was able to train the model .

**Comment by arpit601** [comment]
I think its generating only one decoded path from greeedy_search_decoder  
there is some problem with this part of the code too..
for decoded_path in decoded_ids_paths:	
          decoded_ids = next(decoded_path.values)

**Comment by arpit601** [comment]
@timediv Did you find any error or is it running for you ?

**Comment by louiskirsch** [comment]
I never had this issue and don't know what of your changes could have caused this right now. It basically must mean there is no decoded path in the result from the greedy decoding.
I'll let you know if I can think of something.

**Comment by arpit601** [comment]
@timediv copying a part of your evaluation.py
      for decoded_path in decoded_ids_paths:
        decoded_ids = next(decoded_path)
 I think there is an issue with next(decoded_path) . There is no point running next(decoded_path) when that is the same variable iterating in the outer loop. Is it next(decoded_path) or smthng else ? Also right now ,decoded_path has one path that it is giving.

**Comment by ghost** [comment]
@timediv even I am facing the same issue

**Comment by louiskirsch** [comment]
Okay that's odd. I will look into this.

**Comment by arpit601** [comment]
@timediv  Hey Louis !!! Thanks for giving a prompt reply. I have been able to solve this problem . This error occurred due to insufficient training .

**Comment by louiskirsch** [comment]
@arpit601 Interesting. Can you tell me how I can reproduce the problem. For how long have you trained so that the problem occurred, for how long for the problem to disappear?

**Comment by louiskirsch** [comment]
@arpit601 and @pdcoded I added evaluation details and downloadable pretrained weights to the README!
