### ISSUE TITLE
epochs for training

### ISSUE THREAD

**Issue by arpit601** [timediv/speechT#4]
How do you set the number of epochs for training ?

epoch-count flag comes in evaluation file,..

**Comment by louiskirsch** [comment]
Training goes on until you abort. It outputs whenever it saved `Model saved.`.
You can specify how often it shall save with `--steps-per-checkpoint`

**Comment by arpit601** [comment]
Lets say I put 1000 files for training and give batch size as 10 , then after running it for 1000 global steps what should be the number of epochs ?

**Comment by louiskirsch** [comment]
well epochs = number of iterations through dataset
therefore
```
examples_seen = batch_size * steps
epochs = examples_seen / training_set_size
10 * 1000 / 1000 = 10 epochs
```
