### ISSUE TITLE
Calculating epochs?

### ISSUE THREAD

**Issue by arpit601** [timediv/speechT#5]
@arpit601
arpit601 
commented about 1 hour ago
Lets say I put 1000 files for training and give batch size as 10 , then after running it for 1000 global steps what should be the number of epochs ?

**Comment by louiskirsch** [comment]
well epochs = number of iterations through dataset
therefore
```
examples_seen = batch_size * steps
epochs = examples_seen / training_set_size
10 * 1000 / 1000 = 10 epochs
```

**Comment by arpit601** [comment]
Thanks
