### ISSUE TITLE
Compile kenlm with tensorflow

### ISSUE THREAD

**Issue by arpit601** [timediv/speechT#6]
Hey Louis !!! How did you integrate kenlm with tensorflow ??

As of now tensorflow decoder does not have kenlm argument . I went through the reference given by you also but things are still not clear .

**Comment by louiskirsch** [comment]
Just follow the instructions on how to compile and install tensorflow
https://github.com/timediv/tensorflow-with-kenlm/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources

And use https://github.com/timediv/tensorflow-with-kenlm as the sources.

**Comment by arpit601** [comment]
I have pre installed tensorflow on gpu machine. So, do I have to install tensorflow- with-kenlm from starting again ?

**Comment by louiskirsch** [comment]
yes, but it's not that hard

**Comment by violeta7** [comment]
I encountered "404 not found"with the above link. (https://github.com/timediv/tensorflow-with-kenlm/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources)
Could you please give me any suggestions?

**Comment by lscaria** [comment]
same! could you relink the install from sources documentation?
