### ISSUE TITLE
Not saving  .npz files in the preprocessed folder

### ISSUE THREAD

**Issue by arpit601** [timediv/speechT#7]
After preprocessing, files are not getting stored in the desired folder even though the right directory path has been generated . 

Like for developmental data, the directory path is data/preprocessed-power/dev  but it shows empty directory even after running the preprocessing step.

**Comment by arpit601** [comment]
Does it use power spectrogram as deault preprocessing parameter or mfcc ?

**Comment by louiskirsch** [comment]
Probably your audioread backend does not support flac
Install e.g. ffmpeg and portaudio19-dev
`sudo apt install portaudio19-dev ffmpeg`

We should print an error message if that is the case though.

**Comment by louiskirsch** [comment]
@arpit601 power by default

**Comment by louiskirsch** [comment]
@arpit601 Before installing the necessary packages, can you check whether you get a proper error message with #9 

Thanks!

**Comment by louiskirsch** [comment]
solved in #9
